# Site settings
title: 3D GeoInfo 2018
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  3D GeoInfo conference 2018

baseurl: "/events/3dgeoinfo2018"
url: "https://3d.bk.tudelft.nl" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  hard_wrap:      false
  toc_levels:     2..2

